

# Colores básicos:
NEGRO       = (0,   0,   0)
BLANCO      = (255, 255, 255)

# Grises
GRIS_CLARO  = (230, 230, 230)
GRIS        = (170, 170, 170)
GRIS_OSCURO = (100, 100, 100)

# colores de eventos
COLOR_HOVER = (120, 120, 130)
COLOR_CLICK = (110, 110, 130)
COLOR_NORMAL= GRIS_OSCURO
COLOR_TEXTO = NEGRO

# Colores pastel:
LIL_PASTEL        = "#D6BAFF"
ROSA_PASTEL       = "#FFC4FF"
ROJO_PASTEL       = "#FFA8B1"
MELOCOTON_PASTEL  = "#FFD7B8"
NARANJA_PASTEL    = "#FFEEB8"

AMARILLO_PASTEL   = "#FFFFBA"
VERDE_PASTEL      = "#B8FFB8"
CELESTE_PASTEL    = "#B8FFF0"
AZUL_PASTEL       = "#ADDCFF"
LAVANDER_PASTEL   = "#A1B4FF"

lista_colores_pastel = [LIL_PASTEL,ROSA_PASTEL,ROJO_PASTEL,MELOCOTON_PASTEL,NARANJA_PASTEL,AMARILLO_PASTEL
                        ,VERDE_PASTEL,CELESTE_PASTEL,AZUL_PASTEL,LAVANDER_PASTEL]


